######################## default configuration ####################
baseURL = "https://events.padelmba.com/"
title = "Torneos, Clinics y Campus de competición de Pádel en España/Europa - by PadelMBA, lider en formación de pádel online"
languageCode = "es-es"
defaultContentLanguage = "es"
# defaultContentLang = "es"
#theme = "padelmba"
# post pagination
paginate = "6"
enableInlineShortcodes = true
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "xxxxxx" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = ["fr", "en"] # disable language from here
date_format = "02 Jan 2006"
enableEmoji = true
enableRobotsTXT = false
# Taxonomias para usar en Torneos PadelMBA
[taxonomies]
  categoria = "categorias"
  etiqueta = "etiquetas"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
# [[params.plugins.css]]
# link = "plugins/animate/animate.css"
[[params.plugins.css]]
link = "plugins/venobox/venobox.css"
[[params.plugins.css]] # https://swiperjs.com/get-started#use-swiper-from-cdn
link = "plugins/swiper/swiper-bundle.min.css"
[[params.plugins.css]] # custom icons for events.padelmba.com
link = "plugins/events-padelmba-icons/style.css"
# InstantSearch CSS plugin
[[params.plugins.css]]
link = "plugins/instantsearch/instantsearch.min.css"
# default Algolia theme for the widgets to be effectively styled 
# TODO: Arreglar Algolia Search
# [[params.plugins.css]]
# link = "plugins/instantsearch/instantsearch-theme-algolia.min.css"

# CSS custom plugin for Icons PadelMBA
[[params.icons.css]]
link = "plugins/events-padelmba-icons/style.css"
# [[params.plugins.css]] # custom icons for events.padelmba.com
# link = "plugins/mapbox/mapbox-gl.css"
# [[params.plugins.css]] # carrusel fotos patrocinadores
# link = "plugins/carousel/carousel.css"
# [[params.plugins.css]]
# link = "plugins/themify-icons/themify-icons.css"
# Custom JS for Scroll-Top StickyTabs
# [[params.plugins.js]]
# link = "plugins/custom/custom.js"


# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/venobox/venobox.min.js"
[[params.plugins.js]] # carrusel fotos patrocinadores
link = "plugins/carousel/carousel.js"
[[params.plugins.js]] # https://swiperjs.com/get-started#use-swiper-from-cdn
link = "plugins/swiper/swiper-bundle.min.js"
# InstantSearch JS plugin
# TODO: Arreglar Algolia Search
# [[params.plugins.js]]
# link = "plugins/instantsearch/instantsearch.js"
# [[params.plugins.js]] # https://docs.mapbox.com/mapbox-gl-js/guides/install/
# link = "plugins/mapbox/mapbox-gl.js"
# [[params.plugins.js]]
# link = "plugins/google-map/gmap.js"


#################### default parameters ################################
[params]
noindex = true
### Contacto email y movil fijo de PadelMBA Eventos (Aguado)
contacto_email_eventos = "eventos@padelmba.com"
contacto_wasap_eventos = "608545790"
# Logotipo
logo = "images/logo-padelmba-eventos-2022.svg"
# Meta data
description = "This is meta description SEO, pendiente"
author = "PadelMBA"
# contact info
address = "xxxxx lorem ipsum"
mobile = "+9578454565523"
email = "info@xxxxxxx.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# top header
top_header = false

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader-white-pmba-2022-final.png"


# Subscription
[params.subscription]
enable = true

# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "40.3923732"
map_longitude = "-3.8400133"
map_marker = "images/marker.png" # marker size 37*55 px

# cookies
[params.cookies]
enable = true
expire_days = 2
  
############################# social site ########################
[[params.social]]
title = "Instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://instagram.com/padelmba"

[[params.social]]
title = "Spotify"
icon = "ti-spotify"
link = "https://open.spotify.com/show/243jDg8Ls2JzZDWxsdhQMV"

[[params.social]]
title = "Discord"
icon = "ti-discord"
link = "https://discord.gg/mAj4B85kMH"

[[params.social]]
title = "Youtube"
icon = "ti-youtube"
link = "https://www.youtube.com/channel/UC0HztwdNRoQjjIMz4mWnx7g"

[[params.social]]
title = "Facebook"
icon = "ti-facebook" 
link = "https://www.facebook.com/padelmba"

[[params.social]]
title = "Linkedin"
icon = "ti-linkedin"
link = "https://www.linkedin.com/company/padelmba/"

################################### Spanish language #####################################
[Languages.es]
languageName = "es"
languageCode = "es-es"
contentDir = "content/spanish"
weight = 1
# home = "Inicio"
# copyright
copyright = "Eventos PadelMBA &copy; | Todos los derechos reservados."

#### Algolia Generate Search Index for this ####
# https://forestry.io/blog/search-with-algolia-in-hugo/#2-generating-your-search-index
[outputFormats.Algolia]
baseName = "algolia"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
# vars = ["title", "description", "date", "publishdate", "permalink"]
vars = ["title", "date", "permalink"]
params = ["categorias", "etiquetas", "type", "horario", "nombre_torneo", "club_nombre_torneo", "ciudad_torneo", "precio_desde_torneo", "genero", "imagen_torneo_bottom"]


[outputs]
home = ["HTML", "RSS", "JSON", "Algolia"]
# page = ["HTML", "RSS", "JSON", "Algolia"]
torneo = ["HTML", "RSS", "JSON", "Algolia"]

################### Spanish navigation ####################

# main menu
# [[Languages.es.menu.main]]
# name = "Acerca de"
# url = "acerca-de/"
# weight = 1

[[Languages.es.menu.main]]
lang = "es"
name = "Torneos"
url = "torneos/"
weight = 2

[[Languages.es.menu.main]]
lang = "es"
name = "Circuito PadelMBA"
url = "circuito/"
weight = 3

[[Languages.es.menu.main]]
lang = "es"
name = "Ranking"
url = "ranking/"
weight = 4

# [[Languages.es.menu.main]]
# lang = "es"
# name = "Clinics y MasterClass"
# url = "#"
# weight = 3

# [[Languages.es.menu.main]]
# lang = "es"
# name = "Campus de Competición"
# url = "#"
# weight = 4


################################### English language #####################################
# [Languages.en]
# languageName = "En"
# languageCode = "en-us"
# contentDir = "content/english"
# weight = 2
# home = "Home"
# # copyright
# copyright = "Events PadelMBA &copy; | All rights reserved"


# ################### English navigation ####################

# [[Languages.en.menu.main]]
# name = "Tournaments"
# url = "#"
# weight = 2

# [[Languages.en.menu.main]]
# name = "Clinics"
# url = "#"
# weight = 3

# [[Languages.en.menu.main]]
# name = "Campus"
# url = "#"
# weight = 4

# [[Languages.en.menu.main]]
# name = "Contact"
# url = "#"
# weight = 5


# [markup]
#   [markup.goldmark]
#     [markup.goldmark.renderer]
#       unsafe = true


# [[Languages.es.menu.main]]
# weight = 2
# name = "Eventos"
# hasChildren = true

#   [[Languages.es.menu.main]]
#   parent = "Eventos"
#   name = "torneo"
#   url = "torneo/"

#   [[Languages.es.menu.main]]
#   parent = "Eventos"
#   name = "clinic"
#   url = "#"

#   [[Languages.es.menu.main]]
#   parent = "Eventos"
#   name = "Campus"
#   url = "#"
  
# [[Languages.es.menu.main]]
# name = "Contacto"
# url = "contacto/"
# weight = 3