backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  # name: github
  # repo: frodriguezpmba/eventospmba/ # Path to your GitHub repository

# when using the default proxy server port
local_backend: true
  # when using a custom proxy server port
  # url: http://localhost:1313/admin/
media_folder: "static/imgages/torneos/uploads"
public_folder: "/images/uploads"
collections:
  - name: "torneos"
    label: "Torneos"
    folder: "content/spanish/torneos"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "torneos" }
      - { label: "Fecha del Torneo", name: "fecha", widget: "datetime" }
      - { label: "Horario del Torneo", name: "horario", widget: "string" }
      - { label: "Imagen fondo del Torneo", name: "imagen_fondo_torneo", widget: "image" }
      - { label: "Ficha de Imagen del Torneo (top)", name: "ficha_imagen_torneo_top", widget: "image" }
      - { label: "Ficha de Imagen del Torneo (bottom)", name: "ficha_imagen_torneo_bottom", widget: "image" }
      - { label: "Club del Torneo", name: "club_torneo", widget: "string" }
      - { label: "Contacto Wasap del Torneo", name: "wasap_torneo", widget: "string" }
      - { label: "Contacto Email del Torneo", name: "email_torneo", widget: "string" }
      - { label: "Ids de formulario de Weemss", name: "id_weemss", widget: "number" }
      - { label: "Body", name: "body", widget: "markdown" }
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders
  # Required - a list of locales to show in the editor UI
  locales: [es, en]
  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: es